### ISSUE TITLE
borrow-bag requires rebuild even if nothing has changed

### ISSUE THREAD

**Issue by coder543** [smangelsdorf/borrow-bag#1]
I was testing out Gotham, which depends on borrow-bag, and I noticed that running 'cargo build' twice in a row requires borrow-bag and then gotham and then the example-app to be rebuilt, even if nothing has changed at all.

So, I cloned borrow-bag, and it demonstrates this property of rebuilding every time the build command is issued, rather than realizing nothing has changed.

I'm not sure how to fix this. I tried adding a `[cargo:rerun-if-changed=readme.md](http://doc.crates.io/build-script.html)` print to the build script, but that didn't seem to help.

The only thing that seemed to work was removing the build script, but that seems like a non-solution. Maybe this is a bug with Skeptic.

**Comment by smangelsdorf** [comment]
Thanks for reporting this. I had noticed the rebuilding but thought it was something local / environmental. Maybe there's a tweak to the build script I can make to sort this out, otherwise it'll have to be removed for now.

**Comment by bradleybeddoes** [comment]
In the run up to `Gotham` 0.1 I glossed over this so many times, everything was blissful.

Now it has been reported however I can't help but notice it EVERY SINGLE TIME I do something with a Gotham backed app.

@coder543 has ruined `borrow-bag` for me (well at least until we sort this bug 😏).

**Comment by TimNN** [comment]
This is a known issue with `skeptic`: https://github.com/brson/rust-skeptic/issues/25.

It seems that this can be worked around by adding an empty `readme.md.skt.md` file next to `readme.md`.

**Comment by samsymons** [comment]
I forgot to tag this issue in the PR, but this is closed by https://github.com/smangelsdorf/borrow-bag/pull/2 now.
